parameters:
    ezplatform.fieldtype.matrix.identifier: 'ezmatrix'

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Ibexa\FieldTypeMatrix\FieldType\Type:
        autoconfigure: false
        autowire: true
        public: true
        parent: ezpublish.fieldType
        arguments:
            $fieldTypeIdentifier: '%ezplatform.fieldtype.matrix.identifier%'
        tags:
            - { name: ibexa.field_type, alias: '%ezplatform.fieldtype.matrix.identifier%' }

    Ibexa\FieldTypeMatrix\FieldType\Converter\MatrixConverter:
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: '%ezplatform.fieldtype.matrix.identifier%' }

    Ibexa\FieldTypeMatrix\FieldType\Mapper\MatrixFormMapper:
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: '%ezplatform.fieldtype.matrix.identifier%' }
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: '%ezplatform.fieldtype.matrix.identifier%' }

    Ibexa\FieldTypeMatrix\FieldType\Indexable:
        tags:
            - { name: ibexa.field_type.indexable, alias: '%ezplatform.fieldtype.matrix.identifier%' }
