services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionMapper:
        decorates: EzSystems\EzPlatformGraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper
        arguments:
            $innerMapper: '@Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionMapper.inner'

    Ibexa\FieldTypeMatrix\GraphQL\Schema\NameHelper: ~

    Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionSchemaWorker:
        tags:
            - { name: ezplatform_graphql.domain_schema_worker }

    Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionInputSchemaWorker:
        tags:
            - { name: ezplatform_graphql.domain_schema_worker }

    Ibexa\FieldTypeMatrix\GraphQL\InputHandler:
        tags:
            - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: ezmatrix }

    Ibexa\FieldTypeMatrix\GraphQL\FieldValueResolver:
        tags:
            - {name: overblog_graphql.resolver, alias: "MatrixFieldValue", method: "resolveMatrixFieldValue"}
