services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionMapper:
        decorates: Ibexa\Contracts\GraphQL\Schema\Domain\Content\Mapper\FieldDefinition\FieldDefinitionMapper
        arguments:
            $innerMapper: '@Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionMapper.inner'

    Ibexa\FieldTypeMatrix\GraphQL\Schema\NameHelper: ~

    Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionSchemaWorker:
        tags:
            - { name: ibexa.graphql.domain.schema.worker }

    Ibexa\FieldTypeMatrix\GraphQL\Schema\MatrixFieldDefinitionInputSchemaWorker:
        tags:
            - { name: ibexa.graphql.domain.schema.worker }

    Ibexa\FieldTypeMatrix\GraphQL\InputHandler:
        tags:
            - { name: ibexa.graphql.field_type.input.handler, fieldtype: ezmatrix }

    Ibexa\FieldTypeMatrix\GraphQL\FieldValueResolver:
        tags:
            - {name: overblog_graphql.resolver, alias: "MatrixFieldValue", method: "resolveMatrixFieldValue"}
